apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Values.kubernetes.chart}}-deployment
 labels:
  app: {{.Values.kubernetes.chart}}-deployment

spec:
  selector:
    matchLabels:
      app: {{.Values.kubernetes.chart}}-deployment

  template:
    metadata:
      labels:
        app: {{.Values.kubernetes.chart}}-deployment

    spec:
     containers:
       - name : {{.Values.kubernetes.chart}}-{{.Values.pod.containerName}}-{{.Values.environment}}
         image: {{.Values.pod.imageName}}
         ports:
          - containerPort : {{.Values.pod.containerPort}}
         envFrom :
           - configMapRef:
               name : {{.Values.environment}}-app-config
#we are loading all environment variables from the config map with name :dev-app-config


#helm install helm-release helm-test
#helm upgrade helm-release helm-test