deployment:
  name: angular-kube-deployment
  app: angular-kube-app

pod:
 name: angular-kube-pod
 containerName: angular-kube-container
 imageName: dockerenthusiast1992/kubernetes-angular:161
 containerPort: 80

services:
  name: kube-loadbalancer
  type: LoadBalancer
  appPort: 8081


cluster:
  name: kube-cluster
  appPort: 8085
  type: ClusterIP

environment: ""
