kubernetes:
  chart: angular-nginx-chart
  namespace: angular-nginx-chart-namespace

pod:
 containerName: "container"
 imageName: ""
 containerPort: 80

services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  appPort: 8081

environment: ""
