apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
 type: ClusterIP
 selector:
     app: angular-kube-pod
 ports:
 - port: 8084
   targetPort: 80

#service directs the traffic on port 80 to port 8084 on any pod with selector app=angular-kube-pod
#ClusterIP service is only for internal pod communication